### ISSUE TITLE
Discord link is broken

### ISSUE THREAD

**Issue by errmakov** [icfpcontest2024/icfpcontest2024.github.io#1]
The discord invite link in the footer seems to be broken.

[https://discord.com/invite/PRXDdSjV](https://discord.com/invite/PRXDdSjV)

The result:
![image](https://github.com/icfpcontest2024/icfpcontest2024.github.io/assets/18347555/38599d83-27ed-4c72-bbd4-c0133492505f)

**Comment by jbransen** [comment]
Ugh, again :/ I decided to use Discord because that was used last years, but it's not exactly being friendly to me. Here is a proof that I have (yet again....) set it to never expire...

![image](https://github.com/icfpcontest2024/icfpcontest2024.github.io/assets/1579563/cdf6a257-c07b-41cd-84bd-e5ccc6c2ee7d)

Let's see if it works this time... Anyway, thank you for mentioning!

**Comment by uguu-org** [comment]
It didn't work for me either, I took this screenshot the day before the contest:
![discord](https://github.com/icfpcontest2024/icfpcontest2024.github.io/assets/2000051/f6519881-c10b-4bde-92bc-17b5c8c66bbf)

In previous years a guest account worked, but this year it seemed to require having an existing Discord account.  After solving countless captchas, Discord asked me for a phone number to verify, and that's when I gave up.

The only other contact information listed on the contest site was a twitter account, but icfpcontest2024 did not accept direct messages, so it can't be used for any question that may contain spoilers.  Also, I am told that registering a new twitter account may also require phone number for verification.

Some other fallback communication channel would have been nice, be it an email address or a web form.  No official email address were listed on the site, it would have been awkward for participants to seek out personal addresses of organizers.
